apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-as-a-service
  namespace: naas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: no-as-a-service
  template:
    metadata:
      labels:
        app: no-as-a-service
    spec:
      containers:
      - name: no-as-a-service
        image: ghcr.io/francovare/no-as-a-service:latest
        env:
          - name: TRUSTED_PROXIES
            value: "1"
          - name: PORT
            value: "8080"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
